/**
 * Icon Make It
 * (c) NeroBlu All Rights Reserved.
 */
import UIKit
import NeroBlu

class IconFontSetGenericons: IconFontSet {
    
    var name: String { return "Genericons" }
    
    var linkURL: String { return "http://genericons.com/" }
    
    var licenceURL: String { return "https://raw.githubusercontent.com/Automattic/Genericons/master/LICENSE.txt" }
    
    func font(_ size: CGFloat) -> UIFont { return UIFont(name: "Genericons", size: size)! }
    
    var items: [IconFontItem] { return [
        IconFontItem(text: "\u{f423}", name: "404"),
        IconFontItem(text: "\u{f508}", name: "activity"),
        IconFontItem(text: "\u{f509}", name: "anchor"),
        IconFontItem(text: "\u{f101}", name: "aside"),
        IconFontItem(text: "\u{f416}", name: "attachment"),
        IconFontItem(text: "\u{f109}", name: "audio"),
        IconFontItem(text: "\u{f471}", name: "bold"),
        IconFontItem(text: "\u{f444}", name: "book"),
        IconFontItem(text: "\u{f50a}", name: "bug"),
        IconFontItem(text: "\u{f447}", name: "cart"),
        IconFontItem(text: "\u{f301}", name: "category"),
        IconFontItem(text: "\u{f108}", name: "chat"),
        IconFontItem(text: "\u{f418}", name: "checkmark"),
        IconFontItem(text: "\u{f405}", name: "close"),
        IconFontItem(text: "\u{f406}", name: "close-alt"),
        IconFontItem(text: "\u{f426}", name: "cloud"),
        IconFontItem(text: "\u{f440}", name: "cloud-download"),
        IconFontItem(text: "\u{f441}", name: "cloud-upload"),
        IconFontItem(text: "\u{f462}", name: "code"),
        IconFontItem(text: "\u{f216}", name: "codepen"),
        IconFontItem(text: "\u{f445}", name: "cog"),
        IconFontItem(text: "\u{f432}", name: "collapse"),
        IconFontItem(text: "\u{f300}", name: "comment"),
        IconFontItem(text: "\u{f305}", name: "day"),
        IconFontItem(text: "\u{f221}", name: "digg"),
        IconFontItem(text: "\u{f443}", name: "document"),
        IconFontItem(text: "\u{f428}", name: "dot"),
        IconFontItem(text: "\u{f502}", name: "downarrow"),
        IconFontItem(text: "\u{f50b}", name: "download"),
        IconFontItem(text: "\u{f436}", name: "draggable"),
        IconFontItem(text: "\u{f201}", name: "dribbble"),
        IconFontItem(text: "\u{f225}", name: "dropbox"),
        IconFontItem(text: "\u{f433}", name: "dropdown"),
        IconFontItem(text: "\u{f434}", name: "dropdown-left"),
        IconFontItem(text: "\u{f411}", name: "edit"),
        IconFontItem(text: "\u{f476}", name: "ellipsis"),
        IconFontItem(text: "\u{f431}", name: "expand"),
        IconFontItem(text: "\u{f442}", name: "external"),
        IconFontItem(text: "\u{f203}", name: "facebook"),
        IconFontItem(text: "\u{f204}", name: "facebook-alt"),
        IconFontItem(text: "\u{f458}", name: "fastforward"),
        IconFontItem(text: "\u{f413}", name: "feed"),
        IconFontItem(text: "\u{f468}", name: "flag"),
        IconFontItem(text: "\u{f211}", name: "flickr"),
        IconFontItem(text: "\u{f226}", name: "foursquare"),
        IconFontItem(text: "\u{f474}", name: "fullscreen"),
        IconFontItem(text: "\u{f103}", name: "gallery"),
        IconFontItem(text: "\u{f200}", name: "github"),
        IconFontItem(text: "\u{f206}", name: "googleplus"),
        IconFontItem(text: "\u{f218}", name: "googleplus-alt"),
        IconFontItem(text: "\u{f50c}", name: "handset"),
        IconFontItem(text: "\u{f461}", name: "heart"),
        IconFontItem(text: "\u{f457}", name: "help"),
        IconFontItem(text: "\u{f404}", name: "hide"),
        IconFontItem(text: "\u{f505}", name: "hierarchy"),
        IconFontItem(text: "\u{f409}", name: "home"),
        IconFontItem(text: "\u{f102}", name: "image"),
        IconFontItem(text: "\u{f455}", name: "info"),
        IconFontItem(text: "\u{f215}", name: "instagram"),
        IconFontItem(text: "\u{f472}", name: "italic"),
        IconFontItem(text: "\u{f427}", name: "key"),
        IconFontItem(text: "\u{f503}", name: "leftarrow"),
        IconFontItem(text: "\u{f107}", name: "link"),
        IconFontItem(text: "\u{f207}", name: "linkedin"),
        IconFontItem(text: "\u{f208}", name: "linkedin-alt"),
        IconFontItem(text: "\u{f417}", name: "location"),
        IconFontItem(text: "\u{f470}", name: "lock"),
        IconFontItem(text: "\u{f410}", name: "mail"),
        IconFontItem(text: "\u{f422}", name: "maximize"),
        IconFontItem(text: "\u{f419}", name: "menu"),
        IconFontItem(text: "\u{f50d}", name: "microphone"),
        IconFontItem(text: "\u{f421}", name: "minimize"),
        IconFontItem(text: "\u{f50e}", name: "minus"),
        IconFontItem(text: "\u{f307}", name: "month"),
        IconFontItem(text: "\u{f50f}", name: "move"),
        IconFontItem(text: "\u{f429}", name: "next"),
        IconFontItem(text: "\u{f456}", name: "notice"),
        IconFontItem(text: "\u{f506}", name: "paintbrush"),
        IconFontItem(text: "\u{f219}", name: "path"),
        IconFontItem(text: "\u{f448}", name: "pause"),
        IconFontItem(text: "\u{f437}", name: "phone"),
        IconFontItem(text: "\u{f473}", name: "picture"),
        IconFontItem(text: "\u{f308}", name: "pinned"),
        IconFontItem(text: "\u{f209}", name: "pinterest"),
        IconFontItem(text: "\u{f210}", name: "pinterest-alt"),
        IconFontItem(text: "\u{f452}", name: "play"),
        IconFontItem(text: "\u{f439}", name: "plugin"),
        IconFontItem(text: "\u{f510}", name: "plus"),
        IconFontItem(text: "\u{f224}", name: "pocket"),
        IconFontItem(text: "\u{f217}", name: "polldaddy"),
        IconFontItem(text: "\u{f460}", name: "portfolio"),
        IconFontItem(text: "\u{f430}", name: "previous"),
        IconFontItem(text: "\u{f469}", name: "print"),
        IconFontItem(text: "\u{f106}", name: "quote"),
        IconFontItem(text: "\u{f511}", name: "rating-empty"),
        IconFontItem(text: "\u{f512}", name: "rating-full"),
        IconFontItem(text: "\u{f513}", name: "rating-half"),
        IconFontItem(text: "\u{f222}", name: "reddit"),
        IconFontItem(text: "\u{f420}", name: "refresh"),
        IconFontItem(text: "\u{f412}", name: "reply"),
        IconFontItem(text: "\u{f466}", name: "reply-alt"),
        IconFontItem(text: "\u{f467}", name: "reply-single"),
        IconFontItem(text: "\u{f459}", name: "rewind"),
        IconFontItem(text: "\u{f501}", name: "rightarrow"),
        IconFontItem(text: "\u{f400}", name: "search"),
        IconFontItem(text: "\u{f438}", name: "send-to-phone"),
        IconFontItem(text: "\u{f454}", name: "send-to-tablet"),
        IconFontItem(text: "\u{f415}", name: "share"),
        IconFontItem(text: "\u{f403}", name: "show"),
        IconFontItem(text: "\u{f514}", name: "shuffle"),
        IconFontItem(text: "\u{f507}", name: "sitemap"),
        IconFontItem(text: "\u{f451}", name: "skip-ahead"),
        IconFontItem(text: "\u{f450}", name: "skip-back"),
        IconFontItem(text: "\u{f220}", name: "skype"),
        IconFontItem(text: "\u{f424}", name: "spam"),
        IconFontItem(text: "\u{f515}", name: "spotify"),
        IconFontItem(text: "\u{f100}", name: "standard"),
        IconFontItem(text: "\u{f408}", name: "star"),
        IconFontItem(text: "\u{f105}", name: "status"),
        IconFontItem(text: "\u{f449}", name: "stop"),
        IconFontItem(text: "\u{f223}", name: "stumbleupon"),
        IconFontItem(text: "\u{f463}", name: "subscribe"),
        IconFontItem(text: "\u{f465}", name: "subscribed"),
        IconFontItem(text: "\u{f425}", name: "summary"),
        IconFontItem(text: "\u{f453}", name: "tablet"),
        IconFontItem(text: "\u{f302}", name: "tag"),
        IconFontItem(text: "\u{f303}", name: "time"),
        IconFontItem(text: "\u{f435}", name: "top"),
        IconFontItem(text: "\u{f407}", name: "trash"),
        IconFontItem(text: "\u{f214}", name: "tumblr"),
        IconFontItem(text: "\u{f516}", name: "twitch"),
        IconFontItem(text: "\u{f202}", name: "twitter"),
        IconFontItem(text: "\u{f446}", name: "unapprove"),
        IconFontItem(text: "\u{f464}", name: "unsubscribe"),
        IconFontItem(text: "\u{f401}", name: "unzoom"),
        IconFontItem(text: "\u{f500}", name: "uparrow"),
        IconFontItem(text: "\u{f304}", name: "user"),
        IconFontItem(text: "\u{f104}", name: "video"),
        IconFontItem(text: "\u{f517}", name: "videocamera"),
        IconFontItem(text: "\u{f212}", name: "vimeo"),
        IconFontItem(text: "\u{f414}", name: "warning"),
        IconFontItem(text: "\u{f475}", name: "website"),
        IconFontItem(text: "\u{f306}", name: "week"),
        IconFontItem(text: "\u{f205}", name: "wordpress"),
        IconFontItem(text: "\u{f504}", name: "xpost"),
        IconFontItem(text: "\u{f213}", name: "youtube"),
        IconFontItem(text: "\u{f402}", name: "zoom"),
        ]}
}
